import { Component, inject } from '@angular/core';
import { RuntimeConfigService } from 'shared';

/**
 * The "check in here" call-to-action on the waiting-room board: a QR code plus the plain URL of the public-checkin
 * kiosk, so a visitor can start a check-in from their own phone instead of queuing for a physical kiosk.
 *
 * <p>The QR code is generated by the backend API.</p>
 *
 * <p>The URL itself comes from {@link RuntimeConfig.publicCheckinUrl}, injected into only this app's container at
 * `aspire run` time (see the AppHost + docker/write-runtime-config.sh). When it isn't configured this component
 * renders nothing, so the board simply omits the call-to-action rather than showing a broken link. Note for the
 * POC: that URL is a localhost address (all apps run on the one isolated machine), so the QR is illustrative of the
 * pattern — a phone on a separate network can't reach localhost; a real deployment would inject a routable URL.</p>
 */
@Component({
  selector: 'app-check-in-qr',
  imports: [],
  templateUrl: './check-in-qr.html',
  styleUrl: './check-in-qr.css',
})
export class CheckInQr {
  private readonly config = inject(RuntimeConfigService);

  /** The public-checkin URL to advertise, or null when this deployment didn't configure one (then the CTA is hidden). */
  protected get checkInUrl(): string | null {
    return this.config.get().publicCheckinUrl ?? null;
  }

  /**
   * The API URL that generates the QR code image. Null when there's no check-in URL.
   */
  protected get qrDataUrl(): string | null {
    const url = this.checkInUrl;
    const apiUrl = this.config.get().apiBaseUrl;
    if (!url || !apiUrl) {
      return null;
    }
    return `${apiUrl}/checkin/qr`;
  }
}
